CREATE TABLE `email_template` ( `email_template_id` INT NOT NULL AUTO_INCREMENT ,  `title` LONGTEXT NOT NULL ,  `subject` LONGTEXT NOT NULL ,  `body` LONGTEXT NOT NULL ,    PRIMARY KEY  (`email_template_id`));

INSERT INTO `permission` (`permission_id`, `name`, `codename`, `parent_status`, `description`) VALUES (NULL, 'email_template', 'email_template', 'parent', NULL);

INSERT INTO `email_template` (`email_template_id`, `title`, `subject`, `body`) VALUES
(1, 'Password Reset Email', 'Password Reset Successful', '<p><span [removed]="font-weight: bold;">Hi [[to]],</span></p><p><span [removed]="font-weight: bold;">You recently requested a new password. We''ve received the request and your password has been changed.</span></p><p><span [removed]="font-weight: bold;">Your account type is : [[account_type]]<br></span></p><p><span [removed]="font-weight: bold;">Your new password is : [[password]]</span></p><p><span [removed]="font-weight: bold;">Thanks,</span></p><p><span [removed]="" bold;"="">[[from]]</span></p>'),
(2, 'Account Approval Email', 'Account Approval Status', '<p><span [removed]="font-weight: bold;">Hi [[to]],</span></p><p><span [removed]="font-weight: bold;">Your account type is : [[account_type]]</span></p><p><span [removed]="font-weight: bold;">Email : [[email]]</span></p><p><span [removed]="font-weight: bold;">Thank you for registering at our site. Your registration must be approved by the administrator and your account has been [[status]]. Please contact with the </span>administration team if you have any further question. Best wishes.</p><p><span [removed]="font-weight: bold;"><br></span></p><p><span [removed]="font-weight: bold;">Thanks,</span></p><p><span [removed]="" bold;"="">[[from]]</span></p>'),
(3, 'Membership Upgrade Email', 'Membership Upgraded', '<p><span [removed]="font-weight: bold;">Hi [[to]],</span></p><p><span [removed]="font-weight: bold;">Your account type is : [[account_type]]</span></p><p><span [removed]="font-weight: bold;">Email : [[email]]</span></p><p><span [removed]="font-weight: bold;">Your Membership Type is [[package]]. </span></p><p><span [removed]="font-weight: bold;">Please contact with the </span>administrator team if you have any further question. Best wishes.</p><p><span [removed]="font-weight: bold;"><br></span></p><p><span [removed]="font-weight: bold;">Thanks,</span></p><p><span [removed]="" bold;"="">[[from]]</span></p>'),
(4, 'Account Opening Email', 'Account Opening', '<p><span [removed]="font-weight: bold;">Hi [[to]],</span></p><p><span [removed]="font-weight: bold;">Thank you for registering at our site </span>[[sitename]]<span [removed]="font-weight: bold;">. </span></p><p><span [removed]="font-weight: bold;">Your account type is : [[account_type]]</span></p><p><span [removed]="font-weight: bold;">Email is : [[email]]</span></p><p><span [removed]="font-weight: bold;"></span></p><p><span [removed]="font-weight: bold;">Password is : [[password]]</span></p><p><span [removed]="font-weight: bold;">Your account is now being reviewed by </span>administration team. Please wait for Admin approval. You will get a  confirmation email soon and after that you will be able to login from here : [[url]]</p><p><span [removed]="font-weight: bold;">Please contact with the </span>administration team if you have any further question. Best wishes.<br></p><p><span [removed]="font-weight: bold;"><br></span></p><p><span [removed]="font-weight: bold;">Thanks,</span></p><p><span [removed]="" bold;"="">[[from]]</span></p>');

INSERT INTO `business_settings` (`business_settings_id`, `type`, `status`, `value`) VALUES (NULL, 'c2_set', NULL, 'ok');
INSERT INTO `business_settings` (`business_settings_id`, `type`, `status`, `value`) VALUES (NULL, 'c2_user', NULL, NULL);
INSERT INTO `business_settings` (`business_settings_id`, `type`, `status`, `value`) VALUES (NULL, 'c2_secret', NULL, NULL);
INSERT INTO `business_settings` (`business_settings_id`, `type`, `status`, `value`) VALUES (NULL, 'c2_type', NULL, NULL);
ALTER TABLE `vendor` ADD `c2_set` VARCHAR(20) NULL AFTER `state`, ADD `c2_user` LONGTEXT NULL AFTER `c2_set`, ADD `c2_secret` LONGTEXT NULL AFTER `c2_user`;