ALTER TABLE `user` ADD `country` VARCHAR(100) NULL DEFAULT NULL;
ALTER TABLE `user` ADD `state` VARCHAR(100) NULL DEFAULT NULL;
ALTER TABLE `vendor` ADD `country` VARCHAR(100) NULL DEFAULT NULL;
ALTER TABLE `vendor` ADD `city` VARCHAR(100) NULL DEFAULT NULL;
ALTER TABLE `vendor` ADD `zip` VARCHAR(100) NULL DEFAULT NULL;
ALTER TABLE `vendor` ADD `state` VARCHAR(100) NULL DEFAULT NULL;